services:
  userapi:
    build: ./api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DATABASE_URL=host=db port=5432 user=postgres password=password dbname=mydb sslmode=disable
    restart: unless-stopped

  travelplanapi:
    build: ./travelplanapi
    ports:
      - "8081:8080"
    depends_on:
      - db
    environment:
      - DATABASE_URL=host=db port=5432 user=postgres password=password dbname=mydb sslmode=disable
    restart: unless-stopped

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db_data:
