services:
  krakend_ce:
    # The :watch image restarts the service automatically when the configuration files change.
    # Do not use this image in production, it's meant to speed up your testing and development.
    image: devopsfaith/krakend:watch
    volumes:
      - .:/etc/krakend
    ports:
      - "8080:8080"
    command: ["run", "-d", "-c", "krakend.json"]
    depends_on:
      - userapi
      - travelplanapi

  userapi:
    build: ./api
    ports:
      - "8082:8080"
    depends_on:
      db1:
        condition: service_healthy
    environment:
      - DATABASE_URL=host=db1 port=5432 user=postgres password=password dbname=mydb sslmode=disable
    restart: unless-stopped

  travelplanapi:
    build: ./travelplanapi
    ports:
      - "8081:8080"
    depends_on:
      db2:
        condition: service_healthy
    environment:
      - DATABASE_URL=host=db2 port=5432 user=postgres password=password dbname=mydb sslmode=disable
    restart: unless-stopped

  db1:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 3s
      retries: 5
      start_period: 10s
    volumes:
      - db_data1:/var/lib/postgresql/data
    restart: unless-stopped

  db2:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 3s
      retries: 5
      start_period: 10s
    volumes:
      - db_data2:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db_data1:
  db_data2:
