CREATE TABLE tp_tp_tags (
    id SERIAL PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    edited_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    travel_plan_id INT NOT NULL,
    travel_plan_tag_id INT NOT NULL
);