CREATE TABLE tp_photos (
    photo_id SERIAL PRIMARY KEY,
    id INT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    edited_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    url TEXT NOT NULL,
    travel_plan_id INT NOT NULL
);