networks:
  journey-squad-network:
    driver: bridge

services:
  react-app:
    build: .
    image: frontend
    ports:
      - "3000:3000"
    networks:
      - journey-squad-network

  ngrok:
    image: ngrok/ngrok:latest
    command:
      - "http"
      - "http://host.docker.internal:3000"
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    ports:
      - 4040:4040
    networks:
      - journey-squad-network